import type cytoscape from 'cytoscape';

export const NODE_COLORS: Record<string, string> = {
  ADDomain: '#00f3ff',
  ADForest: '#00b4d8',
  ADOU: '#48cae4',
  ADUser: '#7c4dff',
  ADGroup: '#ff6d00',
  ADComputer: '#00c853',
  ADService: '#76ff03',
  ADCertificate: '#ffd600',
  ADTrust: '#f06292',
  ADSubnet: '#4fc3f7',
  ADSite: '#29b6f6',
  ADPolicy: '#ab47bc',
  ADExposure: '#ff1744',
  ADFinding: '#ff5252',
  ADIdentityProvider: '#ec407a',
  ADVPNGateway: '#ff7043',
  ADAuthService: '#ff8a65',
};

export const NODE_SHAPES: Record<string, string> = {
  ADDomain: '⬡', ADForest: '⬡', ADOU: '▬', ADUser: '●', ADGroup: '■',
  ADComputer: '▬', ADService: '⬠', ADCertificate: '◆', ADTrust: '●',
  ADSubnet: '▬', ADSite: '▬', ADPolicy: '■', ADExposure: '▲',
  ADFinding: '★', ADIdentityProvider: '●', ADVPNGateway: '⬠', ADAuthService: '▬',
};

export const CYTOSCAPE_STYLESHEET: cytoscape.StylesheetStyle[] = [
  {
    selector: 'node',
    style: {
      label: 'data(label)',
      'background-color': '#1a237e',
      color: '#fff',
      'font-size': 10,
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'ellipsis',
      'text-max-width': '80px',
      width: 36,
      height: 36,
    },
  },
  { selector: 'node[type="ADDomain"]',           style: { 'background-color': '#00f3ff', color: '#000', shape: 'hexagon',          width: 56, height: 56, 'font-size': 11, 'font-weight': 700 } },
  { selector: 'node[type="ADForest"]',           style: { 'background-color': '#00b4d8', color: '#000', shape: 'hexagon',          width: 64, height: 64, 'font-size': 12, 'font-weight': 700 } },
  { selector: 'node[type="ADOU"]',               style: { 'background-color': '#48cae4', color: '#000', shape: 'round-rectangle'                                                                    } },
  { selector: 'node[type="ADUser"]',             style: { 'background-color': '#7c4dff',               shape: 'ellipse'                                                                             } },
  { selector: 'node[type="ADGroup"]',            style: { 'background-color': '#ff6d00',               shape: 'rectangle'                                                                           } },
  { selector: 'node[type="ADComputer"]',         style: { 'background-color': '#00c853',               shape: 'round-rectangle'                                                                     } },
  { selector: 'node[type="ADService"]',          style: { 'background-color': '#76ff03', color: '#000', shape: 'pentagon'                                                                           } },
  { selector: 'node[type="ADCertificate"]',      style: { 'background-color': '#ffd600', color: '#000', shape: 'diamond',          width: 44, height: 44                                           } },
  { selector: 'node[type="ADTrust"]',            style: { 'background-color': '#f06292',               shape: 'ellipse'                                                                             } },
  { selector: 'node[type="ADSubnet"]',           style: { 'background-color': '#4fc3f7', color: '#000', shape: 'round-rectangle'                                                                    } },
  { selector: 'node[type="ADSite"]',             style: { 'background-color': '#29b6f6', color: '#000', shape: 'round-rectangle'                                                                    } },
  { selector: 'node[type="ADPolicy"]',           style: { 'background-color': '#ab47bc',               shape: 'rectangle'                                                                           } },
  { selector: 'node[type="ADExposure"]',         style: { 'background-color': '#ff1744',               shape: 'triangle',          width: 48, height: 48                                           } },
  { selector: 'node[type="ADFinding"]',          style: { 'background-color': '#ff5252',               shape: 'star',              width: 48, height: 48                                           } },
  { selector: 'node[type="ADIdentityProvider"]', style: { 'background-color': '#ec407a',               shape: 'ellipse'                                                                             } },
  { selector: 'node[type="ADVPNGateway"]',       style: { 'background-color': '#ff7043',               shape: 'pentagon'                                                                            } },
  { selector: 'node[type="ADAuthService"]',      style: { 'background-color': '#ff8a65',               shape: 'round-rectangle'                                                                     } },
  {
    selector: 'node:parent',
    style: {
      'background-opacity': 0.05,
      'border-width': 1,
      'border-style': 'dashed',
      'border-color': 'rgba(255,255,255,0.2)',
      'text-valign': 'top',
      'font-size': 9,
      color: 'rgba(255,255,255,0.4)',
      padding: '20px',
      label: 'data(label)',
    },
  },
  {
    selector: 'edge',
    style: {
      'line-color': 'rgba(255,255,255,0.15)',
      'target-arrow-color': 'rgba(255,255,255,0.3)',
      'target-arrow-shape': 'triangle',
      'curve-style': 'bezier',
      'font-size': 8,
      label: 'data(label)',
      color: 'rgba(255,255,255,0.35)',
      'text-rotation': 'autorotate',
      width: 1,
    },
  },
  { selector: 'edge[type="AD_TRUSTS"]',           style: { 'line-color': '#f06292', 'line-style': 'dashed', width: 2 } },
  { selector: 'edge[type="AD_EXPOSES"]',          style: { 'line-color': '#ff1744',                          width: 2 } },
  { selector: 'edge[type="AD_MEMBER_OF"]',        style: { 'line-color': 'rgba(124,77,255,0.5)'                      } },
  { selector: 'edge[type="AD_AUTHENTICATES_TO"]', style: { 'line-color': '#ec407a', 'line-style': 'dotted'            } },
  { selector: 'edge[type="AD_ROUTES_THROUGH"]',   style: { 'line-color': '#ff7043', 'line-style': 'dotted'            } },
  { selector: 'node.highlighted', style: { 'border-width': 3, 'border-color': '#fff', opacity: 1 } },
  { selector: 'node.dimmed',      style: { opacity: 0.12 } },
  { selector: 'edge.dimmed',      style: { opacity: 0.04 } },
  { selector: 'node.searched',    style: { 'border-width': 3, 'border-color': '#ffd600', 'border-style': 'solid', opacity: 1 } },
  { selector: 'node:selected',    style: { 'border-width': 3, 'border-color': '#ffffff', opacity: 1 } },
];
