# Generated by Django 3.2.23 on 2026-05-24 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_domain', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('workflow_id', models.CharField(blank=True, help_text='Temporal workflow execution ID', max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict, help_text='Assessment configuration')),
                ('progress', models.JSONField(default=dict, help_text='Current phase progress map')),
            ],
            options={
                'db_table': 'plugin_ad_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ADDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fqdn', models.CharField(blank=True, max_length=500, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
                ('forest_root', models.BooleanField(default=False)),
                ('functional_level', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_count', models.IntegerField(default=0)),
                ('user_count', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
                ('computer_count', models.IntegerField(default=0)),
                ('neo4j_node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='active_directory_backend.adassessment')),
            ],
            options={
                'db_table': 'plugin_ad_domain',
                'unique_together': {('assessment', 'fqdn')},
            },
        ),
        migrations.CreateModel(
            name='ADTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain_name', models.CharField(max_length=500)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('BIDIRECTIONAL', 'Bidirectional')], max_length=20)),
                ('trust_type', models.CharField(choices=[('PARENT_CHILD', 'Parent-Child'), ('CROSS_LINK', 'Cross-Link'), ('EXTERNAL', 'External'), ('FOREST', 'Forest'), ('REALM', 'Realm')], max_length=20)),
                ('is_transitive', models.BooleanField(default=False)),
                ('is_selective_auth', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='active_directory_backend.adassessment')),
                ('source_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_trusts', to='active_directory_backend.addomain')),
            ],
            options={
                'db_table': 'plugin_ad_trust',
            },
        ),
        migrations.CreateModel(
            name='ADGraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(help_text="e.g. 'trust_map', 'exposure_paths'", max_length=100)),
                ('graph_data', models.JSONField(default=dict, help_text='Cytoscape-compatible node/edge payload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_snapshots', to='active_directory_backend.adassessment')),
            ],
            options={
                'db_table': 'plugin_ad_graph_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ADFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('finding_type', models.CharField(max_length=100)),
                ('affected_object', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='active_directory_backend.adassessment')),
            ],
            options={
                'db_table': 'plugin_ad_finding',
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ADExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('exposure_type', models.CharField(choices=[('VPN', 'VPN Gateway'), ('OWA', 'Outlook Web Access'), ('ADFS', 'ADFS'), ('EXCHANGE', 'Exchange Server'), ('WINRM', 'WinRM'), ('SMB', 'SMB'), ('LDAP', 'LDAP'), ('KERBEROS', 'Kerberos'), ('RDP', 'Remote Desktop'), ('OTHER', 'Other')], max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(default=dict)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='active_directory_backend.adassessment')),
                ('correlated_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposures', to='active_directory_backend.addomain')),
            ],
            options={
                'db_table': 'plugin_ad_exposure',
                'ordering': ['-risk_score'],
            },
        ),
    ]
