# Generated by Django 3.2.23 on 2026-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_directory_backend', '0003_adevidencelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adevidencelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
